# Generated by Django 4.1.4 on 2022-12-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_publish_c4286e_idx',
        ),
    ]
